language: node_js
node_js:
- '0.10'
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/crepererum/brainlink.git
  gh-pages
- rm -rf gh-pages/*
- cp -R release/* gh-pages
- cd gh-pages
- git add .
- git add -u .
- git commit -m "$TRAVIS_COMMIT"
- git push -fq origin gh-pages
env:
  global:
    secure: ZhSYXS/zPZheF/0MMq0dEY+NdIWlyNVqNo/QMRqMA4RKc4PE3xhRjzcQjRYDrNwS/xVqSzzCp83FD+4cWdWviIRAKgM0ymirGDdHUPDm26dfUQ7PsTscVFBy8NDw11JqTNJxO1XwNiCTqscj+SnUPh0Tb/88L1CYEFOaFIHaFuw=
